[build]
    NPM_FLAGS="--production"
    YARN_FLAGS="--production"
[context.production.environment]
    NODE_ENV="production"
[context.deploy-preview.environment]
    NODE_ENV="development"
[context.branch-deploy.environment]
    NODE_ENV="development"
